spring.application.name=Task_Board
## H2 Database config
#spring.datasource.url=jdbc:h2:mem:taskdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=sood

# JPA config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## H2 Console (lets you see DB in browser)
#spring.h2.console.enabled=true
